language: android
jdk: oraclejdk8

android:
    components:
        - build-tools-30.0.2

before_install:
    - yes | sdkmanager "platforms;android-30"

script: 
    - ./gradlew test lintDebug --stacktrace
    - ./.codecov.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)

licenses:
    - '.+'

